name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: node_stripe
          MYSQL_ROOT_PASSWORD: dbpassword

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        run: yarn test